# Generated by Django 3.2 on 2023-10-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heat_Life', '0006_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news',
            new_name='new',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
