# Generated by Django 3.2 on 2023-10-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heat_Life', '0007_auto_20231017_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='name',
            field=models.CharField(default='Название', max_length=200),
        ),
    ]
