# Generated by Django 3.2 on 2023-11-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heat_Life', '0010_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='language',
            field=models.CharField(default='EN', max_length=200),
        ),
    ]
