# Generated by Django 3.2 on 2023-11-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heat_Life', '0012_new_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='preview_text',
            field=models.TextField(blank=True, verbose_name='Текст превью'),
        ),
    ]
