# Generated by Django 3.2 on 2023-11-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heat_Life', '0014_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='adress',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
