# Generated by Django 3.2 on 2023-12-08 10:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Heat_Life', '0015_auto_20231118_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='coop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('jt', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='adress',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
