# Generated by Django 3.2 on 2023-12-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heat_Life', '0019_auto_20231209_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_gr_gr',
            new_name='name_gr',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='Цена', max_length=200),
        ),
    ]
