# Generated by Django 3.2 on 2023-12-09 10:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Heat_Life', '0020_auto_20231209_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('adress', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
        ),
    ]
