# Generated by Django 3.2 on 2023-12-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Heat_Life', '0021_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Heat_Life.product'),
        ),
    ]
